### ISSUE TITLE
Create a contributing.md file

### ISSUE THREAD

**Issue by jamesylgan** [mycoleb/MyFirstAPI#4]
https://yangsu.github.io/pull-request-tutorial/ or any other standards as desired, defined in a top level `contributing.md` file

**Comment by mycoleb** [comment]
#### Rules for Contributors

1. Use descriptive comments and variable names for ease in collaboration.

2. Communicate via Discord for planning new code/tasks

### Goals
Create an API using Flask and Open telemetry

a) make an issue per feature
b) work off branches/forks and make PRs (you'll learn git and project management from doing this)
c) document in readme markdown files
